FROM quay.io/wildfly/wildfly:34.0.0.Final-jdk21
LABEL maintainer="Matthias Pischka" description="WildFly mit Deployment"

COPY ./target/primefaces-schnellstart.war $JBOSS_HOME/standalone/deployments/
